SELECT * 
FROM COUNTRIES;

SELECT * 
FROM DEPARTMENTS;

SELECT *
FROM EMPLOYEES

-- this for select any table or column and any thing that you want to.

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60 OR SALARY > 6000

-- this use for conditional selection of all tables AND // OR.


SELECT *
FROM EMPLOYEES
WHERE SALARY = (
	SELECT DISTINCT SALARY
    FROM EMPLOYEES
    ORDER BY SALARY DESC
	LIMIT 1
	OFFSET 1
);

SELECT *
FROM EMPLOYEES 
WHERE SALARY = (
	SELECT MAX(SALARY)
	FROM EMPLOYEES
	WHERE SALARY < (
		SELECT MAX(SALARY)
		FROM EMPLOYEES
	)
);

SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY < (
	SELECT MAX(SALARY)
	FROM EMPLOYEES
);



SELECT *
FROM EMPLOYEES AS EMP
WHERE SALARY > (
		SELECT SALARY
        FROM EMPLOYEES AS MGR
        WHERE EMP.MANAGER_ID = MGR.EMPLOYEE_ID
	);


SELECT *
FROM EMPLOYEES AS EMP
WHERE JOB_ID = (
		SELECT JOB_ID
        FROM EMPLOYEES AS MGR
        WHERE EMP.MANAGER_ID = MGR.EMPLOYEE_ID
	);


-- advanced sub queries

SELECT *
FROM EMPLOYEES
LIMIT 5;


WITH TEMP AS(
SELECT *
FROM EMPLOYEES
LIMIT 5
)
SELECT *
FROM TEMP;

WITH AVGIT AS
(
	SELECT AVG(SALARY) AS SAL1
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = 60 -- IT
),
MAXMKT AS
(
	SELECT MAX(SALARY) AS SAL2
	FROM EMPLOYEES
    WHERE DEPARTMENT_ID = 20 -- MARKETING
)
SELECT *
FROM EMPLOYEES
WHERE SALARY > (SELECT SAL1 FROM AVGIT) AND SALARY < (SELECT SAL2 FROM MAXMKT);


-- Common Table Expressions